version: "3"

tasks:
  dev:
    desc: Start the FastAPI development server
    cmd: uv run uvicorn main:app --reload --host 0.0.0.0 --port 8000

  start:
    desc: Start the FastAPI server
    cmd: uv run python main.py

  lint:
    desc: Run ruff linter
    cmd: uv run ruff check .

  format:
    desc: Format code with ruff
    cmd: uv run ruff format .

  lint-fix:
    desc: Run ruff linter and fix issues
    cmd: uv run ruff check --fix .

  check:
    desc: Run all checks (lint and format check)
    cmds:
      - uv run ruff check .
      - uv run ruff format --check .

  db-up:
    desc: Start PostgreSQL container
    cmd: docker compose up -d postgres

  db-down:
    desc: Stop PostgreSQL container
    cmd: docker compose down

  migrate:
    desc: Run database migrations
    cmd: uv run alembic upgrade head

  migrate-auto:
    desc: Generate migration from model changes
    cmd: uv run alembic revision --autogenerate

  migrate-create:
    desc: Create empty migration file
    cmd: uv run alembic revision