version: "3"

tasks:
  dev:
    desc: Start the FastAPI development server
    cmd: uv run uvicorn main:app --reload --host 0.0.0.0 --port 8000

  start:
    desc: Start the FastAPI server
    cmd: uv run python main.py

  lint:
    desc: Run ruff linter
    cmd: uv run ruff check .

  format:
    desc: Format code with ruff
    cmd: uv run ruff format .

  lint-fix:
    desc: Run ruff linter and fix issues
    cmd: uv run ruff check --fix .

  check:
    desc: Run all checks (lint and format check)
    cmds:
      - uv run ruff check .
      - uv run ruff format --check .