"""add_subtasks_table

Revision ID: c043c4376f56
Revises: c038e874cc8b
Create Date: 2026-01-27 06:11:05.230985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c043c4376f56'
down_revision: Union[str, None] = 'c038e874cc8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subtasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('todo_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('is_compleated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['todo_id'], ['todos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtasks_id'), 'subtasks', ['id'], unique=False)
    op.create_index(op.f('ix_subtasks_todo_id'), 'subtasks', ['todo_id'], unique=False)
    op.create_index(op.f('ix_subtasks_user_id'), 'subtasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subtasks_user_id'), table_name='subtasks')
    op.drop_index(op.f('ix_subtasks_todo_id'), table_name='subtasks')
    op.drop_index(op.f('ix_subtasks_id'), table_name='subtasks')
    op.drop_table('subtasks')
    # ### end Alembic commands ###
